[package]
name = "tsrust-lowering"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Kianse/tsrust-transpiler"
readme = "../../README.md"
description = "TypeScript-ish syntax to Rust transpiler (prototype)"
keywords = ["rust", "transpiler", "typescript", "compiler"]
categories = ["compilers"]

[dependencies]
tsrust-ast = { path = "../ast" }
tsrust-parser = { path = "../parser" }
